### ISSUE TITLE
Python 3.6.9 --packages-select-regex error: module 're' has no attribute 'Pattern'

### ISSUE THREAD

**Issue by yossioo** [colcon/colcon-package-selection#41]
Title says it.

```
$ colcon build --symlink-install --packages-select-regex robot
[0.152s] ERROR:colcon.colcon_core.package_selection:Exception in package selection extension 'select_skip': module 're' has no attribute 'Pattern'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/package_selection/__init__.py", line 198, in _check_package_selection_parameters
    retval = extension.check_parameters(args=args, pkg_names=pkg_names)
  File "/usr/lib/python3/dist-packages/colcon_package_selection/package_selection/select_skip.py", line 58, in check_parameters
    if isinstance(pattern, re.Pattern):
AttributeError: module 're' has no attribute 'Pattern'
                     
Summary: 0 packages finished [0.08s]
```

Tried on Kubuntu 18.04.5 LTS with ROS2 Dashing from Debian, apt upgraded everything to latest.
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
colcon-package-selection 0.2.9

**Comment by dirk-thomas** [comment]
@yossioo Thanks for the report. Please see #42 for a proposed fix. It would be great if you could try it and comment if it resolves the problem for you.

**Comment by yossioo** [comment]
Works like a charm!

I downloaded the repo, checked out your branch `(dirk-thomas/fix-py35-comp)`, and copied the folder `colcon_package_selection` to `/usr/lib/python3/dist-packages/` replacing the existing one.

After these manipulations regex-based selection worked as it supposed to.
